## Chapter 3 - Arrays

In [15]:
import sys, pandas as pd, yfinance as yf, numpy as np, arch
print("Notebook running from:", sys.executable)

Notebook running from: c:\Tools\miniconda3\envs\quant\python.exe


### Exercise 1 - Create an array

In [16]:
# Lists
prices = [170.12, 93.29, 55.28, 145.30, 171.81, 59.50, 100.50]
earnings = [9.2, 5.31, 2.41, 5.91, 15.42, 2.51, 6.79]

# NumPy arrays
prices_array = np.array(prices)
earnings_array = np.array(earnings)

# Print the arrays
print(prices_array)
print(earnings_array)

[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]


### Exercise 2 - Elementwise operations from an array

In [17]:
# Create PE ratio array
pe_array = prices_array/earnings_array

# Print pe_array
print(pe_array)

[18.49130435 17.56873823 22.93775934 24.58544839 11.14202335 23.70517928
 14.8011782 ]


### Exercise 3 - Subsetting elements from an array

In [18]:
# Subset the first three elements
prices_subset_1 = prices_array[0:3]
print(prices_subset_1)

# Subset last three elements 
prices_subset_2 = prices_array[4:]
print(prices_subset_2)

# Subset every third element
prices_subset_3 = prices_array[0:7:3]
print(prices_subset_3)

[170.12  93.29  55.28]
[171.81  59.5  100.5 ]
[170.12 145.3  100.5 ]


### Exercise 4 - Creating a 2D array

In [19]:
# Create a 2D array of prices and earnings
stock_array = np.array([prices, earnings])
print(stock_array)

# Print the shape of stock_array
print(stock_array.shape)

# Print the size of stock_array
print(stock_array.size)

# Transpose stock_array
stock_array_transposed = np.transpose(stock_array)
print(stock_array_transposed)

# Print the shape of stock_array
print(stock_array_transposed.shape)

# Print the size of stock_array
print(stock_array_transposed.size)

[[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
 [  9.2    5.31   2.41   5.91  15.42   2.51   6.79]]
(2, 7)
14
[[170.12   9.2 ]
 [ 93.29   5.31]
 [ 55.28   2.41]
 [145.3    5.91]
 [171.81  15.42]
 [ 59.5    2.51]
 [100.5    6.79]]
(7, 2)
14


### Exercise 5 - Subsetting 2D arrays

In [20]:
# Subset prices from stock_array_transposed
prices = stock_array_transposed[:, 0]
print(prices)

# Subset earnings from stock_array_transposed
earnings = stock_array_transposed[:, 1]
print(earnings)

# Subset the price and earning for first company
company_1 = stock_array_transposed[0]
print(company_1)

[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]
[170.12   9.2 ]


### Exercise 6 - Calculating array stats

In [21]:
# Calculate the mean 
prices_mean = np.mean(prices)
print(prices_mean)

# Calculate the standard deviation 
prices_std = np.std(prices)
print(prices_std)

113.6857142857143
45.51277932221513


### Exercise 7 - Generating a sequence of numbers

In [22]:
# Create and print company IDs
company_ids = np.arange(1, 8, 1)
print(company_ids)

# Use array slicing to select specific company IDs
company_ids_odd = np.arange(1, 8, 2)
print(company_ids_odd)

[1 2 3 4 5 6 7]
[1 3 5 7]


### Exercise 8 - Who's above average

In [23]:
# Find the mean
price_mean = np.mean(prices)

# Create boolean array
boolean_array = (prices>price_mean)
print(boolean_array)

# Select prices that are greater than average
above_avg = prices[boolean_array]
print(above_avg)

[ True False False  True  True False False]
[170.12 145.3  171.81]
